const Discord = require("discord.js");
const ms = require("ms");

module.exports = async (client, interaction, args) => {
  let questions = [
    "What are some date ideas you look forward to?",
    "What are some quirks your partner has that you love?",
    "Do you have a dream home?",
    "Whats your favorite moment/s with your partner?",
    "If you could have dinner with any celebrity (alive or dead), who would it be?",
    "What was one of the silliest things you thought or misunderstood as a kid?",
    "If you could travel anywhere tomorrow, where would you go?",
    "What’s your favorite animal?",
    "What was your favorite TV show as a kid?",
    "How did you find out the secret about Santa and how did you feel?",
    "What was one toy you always wanted as a kid?",
    "Who is your favorite superhero?",
    "Which game show do you think you would perform best on and why?",
    "Which historical figure would you most want to work for?",
    "What’s your favorite tree?",
    "What’s something you’ve always wanted to do but haven’t had the chance?",
    "If you had to be stranded on a deserted island with one person, who would you pick?",
    "If you could pick one superpower, what would you choose?",
    "If you could choose any performer to put on a show at your birthday party, who would you pick?",
    "Who was your first crush?",
    "What would you choose as your last meal?",
    "If you could travel to space for free, would you go?",
    "What’s your favorite season?",
    "House by the beach or in the mountains?",
    "Life in the city or country?",
    "What smell, sound, or taste do you immediately associate with your childhood?",
    "If you could visit any time period, when would you pick?",
    "What is one new invention you think will be commonplace in 30 years?",
    "What everyday item do you think will be obsolete in 30 years?",
    "What’s your favorite book of all time, and whats one you liked recently?",
    "What fictional story or place would you like to live in?",
    "Which US president (alive or dead) would you most like to meet?",
    "If you could be good at any sport, which would you choose?",
    "You get front-row seats to any concert. Which band/artist do you pick?",
    "In the dining experience of your dreams, who would cook for you?",
    "What is one historical event you wish you could have been present for?",
    "What’s your favorite board or card game?",
    "You have to repeat one course you’ve already taken in school. Which do you choose?",
    "If you could drive any type of vehicle, what would it be?",
    "Who was your first kiss?",
    "You are kicked out of the country and must move to another country. Where do you go?",
    "If you could speak another language, what would you choose?",
    "Have you ever been caught telling a lie? Explain.",
    "Have you ever gotten away with telling a lie? Explain.",
    "You get to relive one decade from history. Which do you choose?",
    "What’s your favorite movie?",
    "If you could have tickets to any play or musical, what would you see?",
    "What’s the best joke or surprise you’ve ever pulled on someone?",
    "What is something you’ve always wanted to see or experience in real life?",
    "Describe one embarrassing moment you wish you could erase.",
    "You get to give up one chore for the rest of your life. Which do you pick?",
    "You have to eat the same food for 1 month straight. What do you choose?",
    "What outdoor activity would you like to try?",
    "Would you rather be trapped in a room filled with snakes or spiders?",
    "You get to relive one family vacation. Which one do you choose?",
    "You are going to be roasted on national TV. Who do you want to headline the event?",
    "You have to give up one of these for 1 month: your smartphone or your sense of taste. Which do you choose?",
    "If you could give anyone (alive or dead) a hug, who would you choose?",
    "You get to pick a new Olympic event. What do you choose?",
    "You get to choose any athlete (alive or dead) to be your personal trainer. Who do you pick?",
    "You have to marry a fictional character. Who do you choose?",
    "You can only choose 1 of these, and the other you will never have again. Would you pick chocolate or coffee?",
    "Is there a pet that you’ve always wanted to have?",
    "Do you, or have you ever had, a fear that seems silly?",
    "You can choose anyone to be your personal life coach. Who do you pick?",
    "What’s your favorite flower?",
    "Would you rather live in a mansion but be poor or a shack but be rich?",
    "You have to replace a body part with a cybernetic version. Which do you choose?",
    "What is one physical trait you’ve always been proud of?",
    "Your worst punishment would be touching _______ for 24 hours straight?",
    "If you could change your middle name, would you? To what?",
    "Who would you choose to play James Bond and/or his love interest?",
    "What’s your favorite drink?",
    "If you could learn to make one thing really well, what would it be?",
    "What’s something you secretly enjoy?",
    "You are given a grant to eliminate one of the world’s problems. Which do you choose?",
    "What’s your favorite scent?",
    "Is there a talent you always wished you’d had?",
    "You get a free ticket to travel around the world. Will you go by boat, plane, train, or car?",
    "What’s one exercise you never want to do again?",
    "If you could be gifted with incredible knowledge in one subject, you’d become a super-genius in the field of _______?",
    "What style of art do you like best?",
    "If you could visit any historical site or landmark in the world, where would you choose?",
    "If you could become curator of any museum, which museum would it be?",
    "What is one thing you didn’t think you’d like, but you ended up liking it?",
    "What is one thing you thought you’d love, but you ended up hating it?",
    "You get to choose anyone to be your next-door neighbors. Who do you choose?",
    "If you could choose a single pet (alive or dead) to be immortal, which would you choose?",
    "What’s one seemingly normal thing that really grosses you out?",
    "What is something you think is seriously underrated?",
    "What is something you think is vastly overrated?",
    "If you could have any job in the world and money was no concern, what would you choose?",
    "You are given more money than you ever thought possible. What is the first thing you spend it on?",
    "What cartoon characters would you proudly wear on your underwear?",
    "You have to change your name. What name do you choose?",
    "You have just been locked up for a lengthy prison term. Who is the first person you write a letter to?",
    "Who would you be most excited to get a postcard from?",
    "Only one TV show/series can air for the next 10 years, and you get to choose it. What do you pick?",
    "You must get a tattoo next week. What do you get and where?",
    "If you could be interviewed by anyone about a great accomplishment, who would you choose to interview you?",
    "Would you rather meet an alien or a ghost?",
    "You must carry around a single possession on your person for the rest of your life. What do you pick?",
    "What is your favorite holiday?",
    "You can choose any person (alive or dead) to read you a bedtime story tonight. Who do you choose?",
  ];

  client.embed(
    {
      title: `💞・Lovers Trivia`,
      desc: `Type out your answers and talk it out :3\n**${questions[Math.floor(Math.random() * questions.length)]}**`,
      type: "editreply",
    },
    interaction
  );
};
